import test from 'node:test';import assert from 'node:assert/strict';
import {finishVariants,selectedStyles} from '../public/finishing.mjs';
import {handleApi,imagePrompt} from '../src/server.js';
const input={image:'data:image/jpeg;base64,/9j/AA==',width:1200,height:800};
test('both styles use the same straightened source exactly once',async()=>{let prepared=0;const calls=[];const p={...input,image:'prepared'};const r=await finishVariants({input,styles:selectedStyles('both'),straighten:true,prepare:async()=>{prepared++;return {input:p,result:{status:'corrected'}};},edit:async(i,style)=>{calls.push({i,style});return {image:style};}});assert.equal(prepared,1);assert.deepEqual(calls.map(x=>x.i),[p,p]);assert.deepEqual(Object.keys(r.results),['internal','internal_golden_hour']);assert.equal(r.results.internal.original,'prepared');});
test('partial failure retains first style without retrying either call',async()=>{const calls=[];const r=await finishVariants({input,styles:selectedStyles('both'),edit:async(i,style)=>{calls.push(style);if(style==='internal_golden_hour')throw Error('Provider failed');return {image:'ok'};}});assert.deepEqual(calls,['internal','internal_golden_hour']);assert.equal(r.results.internal.image,'ok');assert.equal(r.errors.length,1);});
test('cancel after first style prevents a second billed request',async()=>{const c=new AbortController(),calls=[];await finishVariants({input,styles:selectedStyles('both'),signal:c.signal,edit:async(i,s)=>{calls.push(s);return {image:'ok'};},onResult:()=>c.abort()});assert.deepEqual(calls,['internal']);});
test('unresolved straightening prevents AI requests',async()=>{await assert.rejects(finishVariants({input,styles:['internal'],straighten:true,prepare:async()=>({input,result:{status:'unresolved'}}),edit:()=>assert.fail('must not call provider')}),/could not resolve/);});
test('styles are validated server-side; prompts distinguish neutral and golden light',async()=>{const origin='https://latitude-hdr-studio.caitmelo.chatgpt.site',request=style=>new Request(origin+'/api/ai/edit',{method:'POST',headers:{'Content-Type':'application/json',origin,'oai-authenticated-user-email':'styles-test'},body:JSON.stringify({...input,style})});assert.equal((await handleApi(request('unknown'),{OPENAI_API_KEY:'test'},()=>assert.fail())).status,400);for(const style of ['internal','internal_golden_hour','dusk','golden_hour','external_day']){const res=await handleApi(request(style),{OPENAI_API_KEY:'test'},async(url,options)=>{assert.equal(options.body.get('prompt'),imagePrompt(style));assert.equal(options.body.get('n'),'1');return Response.json({data:[{b64_json:'/9j/AA=='}]});});assert.equal((await res.json()).style,style);}assert.match(imagePrompt('internal'),/Maintain the photographed time of day/);assert.match(imagePrompt('internal_golden_hour'),/late-afternoon/);});
