import test from 'node:test';import assert from 'node:assert/strict';import {handleApi} from '../src/server.js';
const origin='https://latitude-hdr-studio.caitmelo.chatgpt.site';
const request=(path='/api/ai/enhance',user='user@example.com',payload={image:'data:image/jpeg;base64,/9j/AA=='})=>new Request(origin+path,{method:'POST',headers:{'oai-authenticated-user-email':user,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(payload)});
test('AI requires a valid-length authenticated email and reports missing configuration honestly',async()=>{for(const user of ['',`a${'b'.repeat(254)}`]){const r=await handleApi(request('/api/ai/enhance',user),{});assert.equal(r.status,401);assert.deepEqual(await r.json(),{error:'Sign in with ChatGPT to use AI.'});}const r=await handleApi(request(),{});assert.equal(r.status,503);assert.equal((await r.json()).code,'missing_key');});
test('configuration endpoint never returns the secret',async()=>{const r=await handleApi(new Request(origin+'/api/ai/status',{headers:{'oai-authenticated-user-email':'test@example.com'}}),{OPENAI_API_KEY:'test-private-value'});const body=await r.text();assert.equal(body.includes('test-private-value'),false);assert.equal(JSON.parse(body).configured,true);});
test('AI requires an apply decision and returns bounded global settings',async()=>{let calls=0;const response=await handleApi(request('/api/ai/enhance','success'),{OPENAI_API_KEY:'test-secret'},async(url,options)=>{calls++;assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(options.headers.Authorization,'Bearer test-secret');const b=JSON.parse(options.body);assert.equal(b.store,false);assert.equal(b.text.format.strict,true);assert.deepEqual(b.text.format.schema.required,['apply','ev','compression','saturation','shadows','warmth','tint','windowPull','explanation']);assert.equal(b.input[0].content[1].type,'input_image');return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({apply:true,ev:99,compression:1,saturation:1.35,shadows:.5,warmth:.7,tint:.7,windowPull:.8,explanation:'Gentle adjustment.'})}]}]});});assert.equal(calls,1);assert.equal(response.status,200);const body=await response.json();assert.equal(body.apply,true);assert.equal(body.tone.ev,2);assert.equal(body.tone.warmth,0);assert.equal(body.tone.tint,0);assert.equal(body.tone.saturation,1.05);});
test('AI rejects a completed response without a boolean apply decision',async()=>{const r=await handleApi(request('/api/ai/enhance','missing-apply'),{OPENAI_API_KEY:'test'},async()=>Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({ev:0,compression:0,saturation:1,shadows:0,warmth:0,tint:0,windowPull:0,explanation:'No change.'})}]}]}));assert.equal(r.status,502);assert.match((await r.json()).error,/unusable/);});
test('AI rejects cross-origin and remote image inputs before calling OpenAI',async()=>{const req=request();req.headers.set('Origin','https://other.example');assert.equal((await handleApi(req,{OPENAI_API_KEY:'test'})).status,403);assert.equal((await handleApi(request('/api/ai/enhance','invalid',{image:'https://other.example/image.jpg'}),{OPENAI_API_KEY:'test'})).status,400);});
test('upstream failures do not expose provider messages or secrets',async()=>{const r=await handleApi(request('/api/ai/enhance','failure'),{OPENAI_API_KEY:'test-secret'},async()=>new Response('test-secret',{status:401}));assert.equal(r.status,502);assert.equal((await r.text()).includes('test-secret'),false);});

test('GPT Image finishing sends a real multipart image edit and returns a separate JPEG',async()=>{let called=0;const r=await handleApi(request('/api/ai/edit','image-success',{image:'data:image/jpeg;base64,/9j/AA==',width:1600,height:1067}),{OPENAI_API_KEY:'test-secret'},async(url,options)=>{called++;assert.equal(url,'https://api.openai.com/v1/images/edits');assert.equal(options.headers.Authorization,'Bearer test-secret');assert.ok(options.body instanceof FormData);assert.equal(options.body.get('model'),'gpt-image-2.5-sunburst');assert.equal(options.body.get('quality'),'high');assert.equal(options.body.get('output_format'),'jpeg');assert.equal(options.body.get('size'),'1536x1024');assert.equal(options.body.get('image').type,'image/jpeg');assert.match(options.body.get('prompt'),/Do not add, remove/);return Response.json({data:[{b64_json:'/9j/AA=='}]});});assert.equal(called,1);assert.equal(r.status,200);assert.equal((await r.json()).image,'data:image/jpeg;base64,/9j/AA==');});
test('GPT Image endpoint rejects unauthenticated requests and malformed inputs without contacting OpenAI',async()=>{const fetcher=()=>{throw Error('must not call provider');};assert.equal((await handleApi(request('/api/ai/edit',''),{OPENAI_API_KEY:'test'},fetcher)).status,401);assert.equal((await handleApi(request('/api/ai/edit','bad-size',{image:'data:image/jpeg;base64,/9j/AA==',width:0,height:1024}),{OPENAI_API_KEY:'test'},fetcher)).status,400);});
test('GPT Image provider failures do not expose secrets or masquerade as edited output',async()=>{const r=await handleApi(request('/api/ai/edit','image-rejected',{image:'data:image/jpeg;base64,/9j/AA==',width:1600,height:1067}),{OPENAI_API_KEY:'test-secret'},async()=>new Response('test-secret',{status:403}));assert.equal(r.status,502);const body=await r.json();assert.match(body.error,/access/);assert.equal(JSON.stringify(body).includes('test-secret'),false);assert.equal(body.image,undefined);});

test('image edits block overlapping calls but permit sequential bulk groups',async()=>{let release;const pending=new Promise(r=>release=r),payload={image:'data:image/jpeg;base64,/9j/AA==',width:1200,height:800},env={OPENAI_API_KEY:'test'};const first=handleApi(request('/api/ai/edit','sequence-user',payload),env,async()=>{await pending;return Response.json({data:[{b64_json:'/9j/AA=='}]});});await new Promise(r=>setImmediate(r));assert.equal((await handleApi(request('/api/ai/edit','sequence-user',payload),env)).status,429);release();assert.equal((await first).status,200);assert.equal((await handleApi(request('/api/ai/edit','sequence-user',payload),env,async()=>Response.json({data:[{b64_json:'/9j/AA=='}]}))).status,200);});
