import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import {groupFrames} from '../public/engine.mjs';
test('bulk queue exports before/after pairs, skips invalid sets, and permits preview review',async()=>{
 const elements=new Map(),draws=[],sent=[],archives=[],downloads=[],fetches=[],timers=new Map();let timerID=0;
 const context2d={drawImage(...args){draws.push(args);},clearRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},fillRect(){},putImageData(...args){draws.push(args);}};
 const element=id=>{if(!elements.has(id))elements.set(id,{value:'0',checked:true,width:500,height:100,dataset:{},classList:{toggle(){},add(){},remove(){}},addEventListener(event,fn){this[event]=fn;},getContext(){return context2d;},toDataURL(){return 'data:image/jpeg;base64,/9j/AA==';},click(){downloads.push(this.download);}});return elements.get(id);};
 class Worker{constructor(){Worker.last=this;}postMessage(q){sent.push(q);}terminate(){}}
 const sandbox={AbortController,atob,fetch:async url=>{fetches.push(url);return {ok:true,json:async()=>url==='/api/ai/edit'?{image:'data:image/jpeg;base64,/9j/AA==',model:'gpt-image-2.5-sunburst'}:{configured:true}};},document:{querySelector:s=>element(s),createElement:()=>element('download')},groupFrames,makeZip:async files=>{archives.push(files);return new Blob(['zip']);},Worker,Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},ImageData:class{constructor(data,width,height){Object.assign(this,{data,width,height});}},setTimeout:(fn,ms)=>{timers.set(++timerID,{fn,ms});return timerID;},clearTimeout:id=>timers.delete(id),crossOriginIsolated:true,navigator:{}};
 vm.createContext(sandbox);const src=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8').replace(/^import .*;$/gm,'');vm.runInContext(src,sandbox);
 element('#autoFinish').checked=false;element('#grouping').value='auto';element('#batchFormat').value='pair';element('#quality').value='half';element('#deghost').value='4';element('#split').value='50';
 const frames=[0,1,2,3,4,5,6].map((n)=>({id:String(n),name:'frame'+n+'.cr3',ev:n%2,meta:{timestamp:100+n,camera_model:'test',width:2,height:1}}));
 const emit=d=>Worker.last.onmessage({data:d});emit({kind:'scanned',frames,errors:[]});element('#mergeAllTop').onclick();
 for(let n=0;n<3;n++){const merge=sent.filter(q=>q.kind==='merge').at(-1);assert.equal(merge.frames.length,2);emit({kind:'merged',stats:{width:2,height:1,span:1,frames:2,motionPercent:0,warnings:[]}});const preview={width:2,height:1,data:new Uint8ClampedArray(8),histogram:new Uint32Array(64)};emit({kind:'preview',requestID:merge.requestID,preview,before:preview});assert.equal(sent.at(-1).variant,'before');emit({kind:'exported',blob:new Blob(['before']),format:'png',variant:'before'});assert.equal(sent.at(-1).variant,'after');emit({kind:'exported',blob:new Blob(['after']),format:'png',variant:'after'});}
 await new Promise(resolve=>setImmediate(resolve));assert.equal(archives.length,1);assert.equal(archives[0].length,7);assert.equal(sent.filter(q=>q.kind==='merge').length,3);assert.equal(fetches.filter(url=>url==='/api/ai/enhance').length,0);assert.match(element('#message').textContent,/3 group\(s\) exported/);assert.match(element('#message').textContent,/Set 4/);assert.equal(downloads[0],'latitude_hdr_batch.zip');assert.equal([...timers.values()].filter(t=>t.ms===300000).length,0,'no stale worker timers after bulk completion');
 assert.match(element('#bracketTabs').innerHTML,/Bracket 3/);for(const index of [0,1,2]){element('#bracketTabs').click({target:{closest:()=>({dataset:{select:String(index)}})}});assert.match(element('#previewLabel').textContent,new RegExp('Bracket '+(index+1)));assert.equal(element('#preview').hidden,false);}element('#groups').click({target:{closest:()=>({dataset:{select:'0'}})}});assert.equal(element('#compareControls').hidden,false);assert.equal(element('#png').disabled,true);assert.equal(element('#compareView').disabled,false);assert.ok(draws.some(args=>args.length===7));
 await element('#imageFinish').onclick();for(const id of ['#aiOriginalImage','#aiFinishedImage'])Object.assign(element(id),{complete:true,naturalWidth:2,naturalHeight:1});element('#aiFinishedImage').onload();assert.equal(draws.at(-1)[0],element('#aiFinishedImage'),'main After viewer paints actual AI image');assert.equal(element('#mergedView').textContent,'After · GPT Image');element('#beforeView').onclick();assert.equal(draws.at(-1)[0],element('#aiOriginalImage'),'Before paints exact AI input');element('#compareView').onclick();assert.ok(draws.some(args=>args.length===9&&args[0]===element('#aiOriginalImage')),'comparison crops the original over AI output');assert.equal(element('#imageFinishPanel').hidden,false);assert.equal(element('#downloadAI').disabled,false);assert.equal(element('#aiFinishedImage').src,'data:image/jpeg;base64,/9j/AA==');element('#bracketTabs').click({target:{closest:()=>({dataset:{select:'1'}})}});assert.equal(element('#imageFinishPanel').hidden,true);element('#bracketTabs').click({target:{closest:()=>({dataset:{select:'0'}})}});assert.equal(element('#imageFinishPanel').hidden,false);element('#downloadAI').onclick();assert.match(downloads.at(-1),/_gpt_image.jpg$/);
});

test('individual merge assesses automatically, retains natural rendering when apply is false, and can be disabled',async()=>{
 const elements=new Map(),sent=[],fetches=[];let applyDecision=false;
 const context2d={clearRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},fillRect(){},putImageData(){},drawImage(){}};
 const element=id=>{if(!elements.has(id))elements.set(id,{value:'0',checked:true,width:500,height:100,dataset:{},classList:{toggle(){},add(){},remove(){}},addEventListener(event,fn){this[event]=fn;},getContext(){return context2d;},click(){}});return elements.get(id);};
 class Worker{constructor(){Worker.last=this;}postMessage(q){sent.push(q);}terminate(){}}
 const fetch=async(url)=>{fetches.push(url);if(url==='/api/ai/status')return {ok:true,status:200,json:async()=>({configured:true})};return {ok:true,status:200,json:async()=>({apply:applyDecision,tone:{ev:1,compression:1,saturation:1.2,shadows:.4,warmth:0,tint:0,windowPull:.4},explanation:applyDecision?'A mild global adjustment helps.':'The natural rendering is balanced.'})};};
 const sandbox={fetch,document:{querySelector:s=>element(s),createElement:tag=>tag==='canvas'?{width:0,height:0,getContext:()=>context2d,toDataURL:()=> 'data:image/jpeg;base64,/9j/AA=='}:element('download')},groupFrames,makeZip:async()=>new Blob(),Worker,Blob,AbortController,URL:{createObjectURL:()=>'',revokeObjectURL(){}},ImageData:class{constructor(data,width,height){Object.assign(this,{data,width,height});}},setTimeout:()=>1,clearTimeout(){},crossOriginIsolated:true,navigator:{}};
 vm.createContext(sandbox);const src=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8').replace(/^import .*;$/gm,'');vm.runInContext(src,sandbox);
 element('#autoFinish').checked=false;element('#grouping').value='auto';element('#quality').value='half';element('#deghost').value='4';element('#split').value='50';
 const frames=[0,1].map(n=>({id:String(n),name:'frame'+n+'.cr3',ev:n,meta:{timestamp:100+n,camera_model:'test',width:2,height:1}}));
 const emit=d=>Worker.last.onmessage({data:d});emit({kind:'scanned',frames,errors:[]});element('#merge').onclick();let merge=sent.find(q=>q.kind==='merge');const preview={width:2,height:1,data:new Uint8ClampedArray(8),histogram:new Uint32Array(64)};emit({kind:'merged',stats:{width:2,height:1,span:1,frames:2,motionPercent:0,warnings:[]}});emit({kind:'preview',requestID:merge.requestID,preview,before:preview});await new Promise(resolve=>setImmediate(resolve));assert.equal(fetches.filter(url=>url==='/api/ai/enhance').length,1);assert.equal(element('#compression').value,1.2);assert.match(element('#message').textContent,/no adjustment was required/);
 element('#autoAssess').checked=false;element('#merge').onclick();merge=sent.filter(q=>q.kind==='merge').at(-1);emit({kind:'merged',stats:{width:2,height:1,span:1,frames:2,motionPercent:0,warnings:[]}});emit({kind:'preview',requestID:merge.requestID,preview,before:preview});await new Promise(resolve=>setImmediate(resolve));assert.equal(fetches.filter(url=>url==='/api/ai/enhance').length,1);
 applyDecision=true;element('#autoAssess').checked=true;element('#merge').onclick();merge=sent.filter(q=>q.kind==='merge').at(-1);emit({kind:'merged',stats:{width:2,height:1,span:1,frames:2,motionPercent:0,warnings:[]}});emit({kind:'preview',requestID:merge.requestID,preview,before:preview});await new Promise(resolve=>setImmediate(resolve));assert.equal(fetches.filter(url=>url==='/api/ai/enhance').length,2);assert.equal(element('#exposure').value,1);assert.equal(element('#aiRevert').disabled,false);element('#aiRevert').onclick();assert.equal(element('#exposure').value,0);
});

test('automatic bulk AI runs once per group and adds separate JPEGs without stale timers',async()=>{
 const elements=new Map(),draws=[],sent=[],archives=[],downloads=[],fetches=[],timers=new Map();let timerID=0;
 const context2d={drawImage(...args){draws.push(args);},clearRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},fillRect(){},putImageData(...args){draws.push(args);}};
 const element=id=>{if(!elements.has(id))elements.set(id,{value:'0',checked:true,width:500,height:100,dataset:{},classList:{toggle(){},add(){},remove(){}},addEventListener(event,fn){this[event]=fn;},getContext(){return context2d;},toDataURL(){return 'data:image/jpeg;base64,/9j/AA==';},click(){downloads.push(this.download);}});return elements.get(id);};
 class Worker{constructor(){Worker.last=this;}postMessage(q){sent.push(q);}terminate(){}}
 const sandbox={AbortController,atob,fetch:async url=>{fetches.push(url);return {ok:true,json:async()=>url==='/api/ai/edit'?{image:'data:image/jpeg;base64,/9j/AA==',model:'gpt-image-2.5-sunburst'}:{configured:true}};},document:{querySelector:s=>element(s),createElement:()=>element('download')},groupFrames,makeZip:async files=>{archives.push(files);return new Blob(['zip']);},Worker,Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},ImageData:class{constructor(data,width,height){Object.assign(this,{data,width,height});}},setTimeout:(fn,ms)=>{timers.set(++timerID,{fn,ms});return timerID;},clearTimeout:id=>timers.delete(id),crossOriginIsolated:true,navigator:{}};
 vm.createContext(sandbox);const src=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8').replace(/^import .*;$/gm,'');vm.runInContext(src,sandbox);
 element('#autoFinish').checked=true;element('#grouping').value='auto';element('#batchFormat').value='pair';element('#quality').value='half';element('#deghost').value='4';element('#split').value='50';
 const frames=[0,1,2,3,4,5,6].map((n)=>({id:String(n),name:'frame'+n+'.cr3',ev:n%2,meta:{timestamp:100+n,camera_model:'test',width:2,height:1}}));
 const emit=d=>Worker.last.onmessage({data:d});emit({kind:'scanned',frames,errors:[]});await new Promise(resolve=>setImmediate(resolve));element('#mergeAllTop').onclick();
 for(let n=0;n<3;n++){const merge=sent.filter(q=>q.kind==='merge').at(-1);assert.equal(merge.frames.length,2);emit({kind:'merged',stats:{width:2,height:1,span:1,frames:2,motionPercent:0,warnings:[]}});const preview={width:2,height:1,data:new Uint8ClampedArray(8),histogram:new Uint32Array(64)};emit({kind:'preview',requestID:merge.requestID,preview,before:preview});assert.equal(sent.at(-1).variant,'before');emit({kind:'exported',blob:new Blob(['before']),format:'png',variant:'before'});assert.equal(sent.at(-1).variant,'after');emit({kind:'exported',blob:new Blob(['after']),format:'png',variant:'after'});await new Promise(resolve=>setImmediate(resolve));}
 await new Promise(resolve=>setImmediate(resolve));assert.equal(archives.length,1);assert.equal(archives[0].length,10);assert.equal(sent.filter(q=>q.kind==='merge').length,3);assert.equal(fetches.filter(url=>url==='/api/ai/enhance').length,0);assert.equal(fetches.filter(url=>url==='/api/ai/edit').length,3);assert.match(element('#message').textContent,/3 group\(s\) exported/);assert.match(element('#message').textContent,/Set 4/);assert.equal(downloads[0],'latitude_hdr_batch.zip');assert.equal([...timers.values()].filter(t=>t.ms===300000).length,0,'no stale worker timers after bulk completion');
 assert.match(element('#bracketTabs').innerHTML,/Bracket 3/);for(const index of [0,1,2]){element('#bracketTabs').click({target:{closest:()=>({dataset:{select:String(index)}})}});assert.match(element('#previewLabel').textContent,new RegExp('Bracket '+(index+1)));assert.equal(element('#preview').hidden,false);}element('#groups').click({target:{closest:()=>({dataset:{select:'0'}})}});assert.equal(element('#compareControls').hidden,false);assert.equal(element('#png').disabled,true);assert.equal(element('#compareView').disabled,false);assert.ok(draws.some(args=>args.length===7));
});

test('bulk AI failure keeps original exports and continues subsequent groups',async()=>{
 const elements=new Map(),draws=[],sent=[],archives=[],downloads=[],fetches=[],timers=new Map();let timerID=0;
 const context2d={drawImage(...args){draws.push(args);},clearRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},fillRect(){},putImageData(...args){draws.push(args);}};
 const element=id=>{if(!elements.has(id))elements.set(id,{value:'0',checked:true,width:500,height:100,dataset:{},classList:{toggle(){},add(){},remove(){}},addEventListener(event,fn){this[event]=fn;},getContext(){return context2d;},toDataURL(){return 'data:image/jpeg;base64,/9j/AA==';},click(){downloads.push(this.download);}});return elements.get(id);};
 class Worker{constructor(){Worker.last=this;}postMessage(q){sent.push(q);}terminate(){}}
 const sandbox={AbortController,atob,fetch:async url=>{fetches.push(url);if(url==='/api/ai/edit'&&fetches.filter(x=>x===url).length===1)return {ok:false,json:async()=>({error:'Provider unavailable'})};return {ok:true,json:async()=>url==='/api/ai/edit'?{image:'data:image/jpeg;base64,/9j/AA==',model:'gpt-image-2.5-sunburst'}:{configured:true}};},document:{querySelector:s=>element(s),createElement:()=>element('download')},groupFrames,makeZip:async files=>{archives.push(files);return new Blob(['zip']);},Worker,Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},ImageData:class{constructor(data,width,height){Object.assign(this,{data,width,height});}},setTimeout:(fn,ms)=>{timers.set(++timerID,{fn,ms});return timerID;},clearTimeout:id=>timers.delete(id),crossOriginIsolated:true,navigator:{}};
 vm.createContext(sandbox);const src=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8').replace(/^import .*;$/gm,'');vm.runInContext(src,sandbox);
 element('#autoFinish').checked=true;element('#grouping').value='auto';element('#batchFormat').value='pair';element('#quality').value='half';element('#deghost').value='4';element('#split').value='50';
 const frames=[0,1,2,3,4,5,6].map((n)=>({id:String(n),name:'frame'+n+'.cr3',ev:n%2,meta:{timestamp:100+n,camera_model:'test',width:2,height:1}}));
 const emit=d=>Worker.last.onmessage({data:d});emit({kind:'scanned',frames,errors:[]});await new Promise(resolve=>setImmediate(resolve));element('#mergeAllTop').onclick();
 for(let n=0;n<3;n++){const merge=sent.filter(q=>q.kind==='merge').at(-1);assert.equal(merge.frames.length,2);emit({kind:'merged',stats:{width:2,height:1,span:1,frames:2,motionPercent:0,warnings:[]}});const preview={width:2,height:1,data:new Uint8ClampedArray(8),histogram:new Uint32Array(64)};emit({kind:'preview',requestID:merge.requestID,preview,before:preview});assert.equal(sent.at(-1).variant,'before');emit({kind:'exported',blob:new Blob(['before']),format:'png',variant:'before'});assert.equal(sent.at(-1).variant,'after');emit({kind:'exported',blob:new Blob(['after']),format:'png',variant:'after'});await new Promise(resolve=>setImmediate(resolve));}
 await new Promise(resolve=>setImmediate(resolve));assert.equal(archives.length,1);assert.equal(archives[0].length,9);assert.equal(sent.filter(q=>q.kind==='merge').length,3);assert.equal(fetches.filter(url=>url==='/api/ai/enhance').length,0);assert.equal(fetches.filter(url=>url==='/api/ai/edit').length,3);assert.match(element('#message').textContent,/3 group\(s\) exported/);assert.match(element('#message').textContent,/Set 4/);assert.equal(downloads[0],'latitude_hdr_batch.zip');assert.equal([...timers.values()].filter(t=>t.ms===300000).length,0,'no stale worker timers after bulk completion');
 assert.match(element('#bracketTabs').innerHTML,/Bracket 3/);for(const index of [0,1,2]){element('#bracketTabs').click({target:{closest:()=>({dataset:{select:String(index)}})}});assert.match(element('#previewLabel').textContent,new RegExp('Bracket '+(index+1)));assert.equal(element('#preview').hidden,false);}element('#groups').click({target:{closest:()=>({dataset:{select:'0'}})}});assert.equal(element('#compareControls').hidden,false);assert.equal(element('#png').disabled,true);assert.equal(element('#compareView').disabled,false);assert.ok(draws.some(args=>args.length===7));
});
